site_name: "PGDTools"

theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - navigation.footer
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

site_url: https://pgdtools.readthedocs.io
repo_url: https://github.com/NASA-Planetary-Science/pgdtools
site_author: Reto Trappitsch

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true


plugins:
  - search
  - mkdocs-jupyter


nav:
  - Home: index.md
  - User guide:
      - Installation: users/install.md
      - Database management: users/db.md
      - Examples:
          - SiC M GCE plot: examples/sic_m_gce.ipynb
  - Maintainer guide:
      - Overview: maintainer/overview.md
      - Add new database: maintainer/db_addition.md
