# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package PyPi

on:
  release:
    types: [created]

jobs:
  deploy:
    if: github.repository_owner == 'NASA-Planetary-Science'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
    - name: Sync Rye
      run: |
        rye sync --all-features
    - name: Build and publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: |
        rye build
        rye publish --toke $PYPI_TOKEN --yes
